### ISSUE TITLE
How to handle Control Point scenarios in version 3.x

### ISSUE THREAD

**Issue by kwhitley** [haremlife/AnimationPoser#3]
So I like where your head is at in the migration to 3.x, because IdlePoser definitely was not perfect when trying to trigger state changes, much less coordinating across multiple idle posers to accomplish what you've enabled with layers, but...

Control Points in particular were incredibly useful in creating bezier curve "in-between" points, allowing for much more fluid movement, but in particular, movement that could navigate obstacles.  This appears to be completely lacking in 3.x, leaving only linear/jerky and often collision-riddled movement.

For instance if an actor is touching their hip in one state, and their shoulder in another, I might have a couple control points (shared across many other such states), one for well outside of the hips, and one for way in front of the shoulder.  By using those, I ensure the hand doesn't drag awkwardly across the body, but rather away from the surface in order to avoid colliding.

Using 2.x I've been able to make incredibly smooth multi-layer animations given the full control of IdlePoser (obviously while lacking any coordination or ability to sync anything, transition animations, etc), but have been unable to do anything even remotely like that in 3.x.

How do you do this in the new system?

**Comment by haremlife** [comment]
Hey @kwhitley ! In my particular experience with the plugin, I haven't so far had issues with the "excessive linearity" of the curves. That MIGHT be because I experience very low framerates, and this makes the curves smooth out naturally.

However, I am aware that bezier curves are important for animators. Removing control points and intermediate states was a decision aiming at simplifying the plugin, but the entire logic for bezier curves is still there, and can be used again.

My idea was to have every state work as a control point. This happens, for example, in Timeline, where there are not "regular keyframes" and "control keyframes", just keyframes.

So, mathematically, what the plugin will do is sort the next N states from the markov chain in advance. So, if you are at state i, the next N states will be sorted, and you have a list (i,N+i) of states. Then you can interpolate those N (say, N=4) positions with a bezier curve. Upon arrival at the next state, say, i+1, the state N+i+1 is going to be sorted, and the average between the (i,N+i) bezier curve and the (i+1,N+i+1) curve will be calculated.

This way you don't have to explicitly define control points, etc; the plugin takes care of the interpolation.

However, I plan on creating a slider that can be used for determining the degree to which the curve should stick to a given state.

All of this is a little difficult for me to do right now, and the work would probably be made much easier if I fix the debugger first. The debugger was something present in IdlePoser which showed the curves, but it stopped working after so many changes I introduced, and I didn't investigate the issue further yet.

Anyway, any help is very welcome.

In conceptual terms, do you think this solution makes sense?

**Comment by haremlife** [comment]
@kwhitley Version 3.8 added Timelines, so that you can have keyframe animation with proper Bezier curve spline interpolation!
